## Numpy
## listeleri arraya çevirme işlemi
## arage,zeros,ones,linspace,eye,random,min,max,argmax,argmin,randn,randint,shape,reshape fonksiyonları
## arrayler ile 4 işlem
 numpy array

In [1]:
import numpy as np

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [6]:
matrixListesi[1][0]

20

In [7]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [15]:
# 0 dan 20 ye kadar git ve 5 eşit parçaya böl
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

# eye

In [16]:
#birim matris
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [17]:
np.random.randn(8)

array([ 0.67699085, -0.20166723, -0.11444993, -1.34686576,  0.48901248,
        1.65901024,  0.32783103, -1.00998208])

In [18]:
np.random.randn(4,4)

array([[ 2.00372095,  0.24667608,  0.6818374 , -2.04103992],
       [ 0.14725565, -0.17980567, -1.06824953, -1.17960347],
       [-0.57433542, -1.29707533, -1.80732212, -1.73098475],
       [ 0.16860809,  0.65637829, -0.35887   , -1.25239355]])

In [19]:
# tek bir eleman döndürmek için
#son yazılan sayıyı almaz 10 gelmez yani hiç
np.random.randint(1,10)

7

In [20]:
np.random.randint(1,100,5)

array([75, 11, 62,  4, 51])

In [21]:
benimNumpyDizim = np.arange(30)
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
benimRandomDizim = np.random.randint(0,100,30)
benimRandomDizim

array([ 7, 12, 95, 18, 66, 91, 85, 12, 74, 51, 76, 84, 57, 47, 34, 32, 94,
       47, 17,  6, 98, 63, 87,  5, 19, 92, 56, 26, 94, 59])

## numpy dizi methodları

In [23]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
benimNumpyDizim.max()

29

In [25]:
benimRandomDizim.max()

98

In [26]:
#max elemanın hangi sırada olduğunu göstericek
benimRandomDizim.argmax()

20

In [27]:
benimNumpyDizim.shape

(30,)

In [28]:
reshapeDizim=benimNumpyDizim.reshape(5,6)
reshapeDizim.shape

(5, 6)

## numpy operasyonlar

In [29]:
benimDizim = np.arange(0,15)
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
benimDizim[5]

5

In [31]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [32]:
benimDizim[3:8] = -5
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [33]:
baskaDizi = np.arange(0,24)

In [34]:
slicingDizisi = baskaDizi[4:9]

In [35]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [36]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [37]:
slicingDizisi[:] = 700

In [38]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [39]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## Burada Slicing yapılıp elemanları değiştirme işlemi yapıldıktan sonra dizimizin kopyası üzerinden işlem yapıldığı için ana dizinin değişmediğini görüyoruz

In [40]:
 ornekDizi = np.arange(0,24)

In [41]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [42]:
ornekDiziKopyasi = ornekDizi.copy()
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [43]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[4:9]
ornekDiziKopyaSlicing

array([4, 5, 6, 7, 8])

In [44]:
ornekDiziKopyaSlicing[:] = 700

In [45]:
ornekDiziKopyaSlicing

array([700, 700, 700, 700, 700])

In [46]:
ornekDiziKopyasi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [47]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [48]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [49]:
benimMatrixDizim = np.array(benimListem)

In [50]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [51]:
benimMatrixDizim[0]

array([10, 20, 30])

In [52]:
# benimMatrixDizim[1,2]
benimMatrixDizim[1][2]

40

In [53]:
benimMatrixDizim[1:,2]

array([40, 60])

In [54]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,16,18,19],[20,21,22,23,24,]]

In [55]:
yeniMatrix = np.array(yeniListe)
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 16, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [57]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [58]:
yeniBirDizi = np.random.randint(1,100,20)

In [59]:
yeniBirDizi

array([44, 30, 60, 19, 26, 50,  2, 35, 82, 17, 19, 41, 68,  1, 77, 36, 82,
       33, 30,  9])

In [60]:
yeniBirDizi > 24

array([ True,  True,  True, False,  True,  True, False,  True,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True, False])

In [61]:
sonucDizisi = yeniBirDizi > 24
sonucDizisi

array([ True,  True,  True, False,  True,  True, False,  True,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True, False])

In [62]:
yeniBirDizi

array([44, 30, 60, 19, 26, 50,  2, 35, 82, 17, 19, 41, 68,  1, 77, 36, 82,
       33, 30,  9])

In [63]:
#sadece 24ten büyük olanları verecek
yeniBirDizi[sonucDizisi]

array([44, 30, 60, 26, 50, 35, 82, 41, 68, 77, 36, 82, 33, 30])

In [64]:
sonDizi = np.arange(0,24)

In [65]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [66]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [67]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [68]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [69]:
sonDizi / sonDizi

C:\Users\MONSTER\AppData\Local\Temp\ipykernel_4396\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [70]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [71]:
np.max(sonDizi)

23

## Levent Aslan BTK akademi numpy kütüphanesi ile çalışmasındaki örnek kodlar